// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from '@shared/constants/supabase';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export default supabase;
export { supabase };