// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://iurstpwtdnlmpvwyhqfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1cnN0cHd0ZG5sbXB2d3locWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4NjAzNDMsImV4cCI6MjA4MTQzNjM0M30.pGCrGsPACMxGgsnMDZf-J-kszQPB1N5y008w_KOj-3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);